### PR TITLE
version: post-release bump

### PR DESCRIPTION
**Pull request by lnielsen**
Signed-off-by: Lars Holm Nielsen <lars.holm.nielsen@cern.ch>

### CODE REVIEW

**Comment by krzysztof** [comment]
LGTM

**Comment by krzysztof** [comment]
@lnielsen I don't have push rights to master

**Comment by lnielsen** [comment]
@krzysztof Can you try again

**Comment by krzysztof** [comment]
@lnielsen still the same thing

**Comment by jirikuncar** [comment]
@krzysztof it should be fixed now
image

**Comment by lnielsen** [comment]
@krzysztof Can you check if you can merge this PR now.

**Comment by lnielsen** [comment]
@krzysztof Ping

**Comment by krzysztof** [comment]
@lnielsen still nothing

```
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: You're not authorized to push to this branch. Visit https://help.github.com/articles/about-protected-branches/ for more information.
To github.com:inveniosoftware/invenio-openaire.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'git@github.com:inveniosoftware/invenio-openaire.git'
```

**Pull request merged**
